config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "pages#dashboard"
  end

  unauthenticated do |user|
    root to: "pages#home"
  end

  resources :conditions, only: [] do
    get "fields", on: :member
  end

  resources :calls, only: [:new, :create]
  namespace :call do
    get "emergencies", to: "emergencies#create"
  end

  resources :hospitals, only: [] do
    get :dashboard, on: :member, as: :dashboard
  end

  if Rails.env.development?
    get 'kitchen_sink', to: 'pages#kitchen_sink'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def to_sym
    self.class.name.downcase.to_sym
  end

  def to_fk
    "#{self.class.name.downcase}_id".to_sym
  end

  def to_table_name
    ActiveSupport::Inflector.pluralize(self.class.name.downcase)
  end
end

app/models/call.rb
class Call < ApplicationRecord
  VALID_GENDERS = ["Male", "Female"]

  belongs_to :user
  belongs_to :hospital
  belongs_to :condition

  def permitted_fields
    condition.fields.map(&:name).map(&:to_sym)
  end

  def details
    super.map do |name, value|
      Call::Detail.new(name, value)
    end
  end
end

app/models/call/broadcaster.rb
class Call::Broadcaster
  def initialize(call)
    @helpers = ActionController::Base.new
    @call = call
  end

  def call
    ActionCable.server.broadcast(
      "hospital_#{@call.hospital.id}_calls",
      {
        id: @call.id,
        card: @helpers.render_to_string(partial: "hospitals/call_card", locals: { call: @call }),
        content: @helpers.render_to_string(partial: "calls/show", locals: { call: @call }),
      }
    )
  end
end

app/models/call/detail.rb
class Call::Detail
  attr_reader :name, :value
  def initialize(name, value)
    @name = name
    @value = value
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :conditions

  def slug
    name.parameterize
  end
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :category
  has_many :calls

  def fields
    super.map do |name, data|
      Field.new(name, data)
    end
  end
end

app/models/field.rb
class Field
  attr_reader :name, :type, :values
  def initialize(name, data = {})
    @name = name
    @type = data["type"]
    @values = data["values"]
  end
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :calls
  has_many :users
  validates :name, :address, presence: true

  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :hospital, optional: true
  has_many :calls

  def paramedic?
    hospital.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    if current_user.hospital
      dashboard_hospital_path(current_user.hospital)
    else
      new_call_path
    end
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/call/emergencies_controller.rb
class Call::EmergenciesController < ApplicationController
  def create
    @call = Call.new
    @call.critical  = true
    @call.hospital  = Hospital.find(params[:hospital_id])
    @call.condition = Condition.find(params[:condition_id])
    @call.user      = current_user

    @call.save!

    Call::Broadcaster.new(@call).call

    redirect_to new_call_path, notice: "Info sent"
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def new
    @call = Call.new
    @hospitals = Hospital.all
  end

  def create
    @call = Call.new(call_params)
    @call.details = details_params
    @call.user = current_user

    if @call.save
      Call::Broadcaster.new(@call).call

      flash[:notice] = "Info sent"
      redirect_to new_call_path
    else
      render :new
    end
  end

  private

  def call_params
    params
      .require(:call)
      .permit(:gender, :age, :blood_pressure, :pulse, :temperature, :spa02, :condition_id, :hospital_id)
  end

  def details_params
    #fix me
    params.require(:call).require(:details).permit(
      @call.permitted_fields,
      radiating_to: [],
      chest_pain_meds: [],
      chest_pain_quality: [],
      chest_pain_relieved_by: [],
      chest_pain_worsened_by: [],
      chest_pain_past_history: [],
      chest_pain_associated_symptoms: [],
      burn_meds: [],
      burn_context: [],
      burn_facial: [],
      burn_location: [],
      burn_meds: []
      )
  end
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  def fields
    @condition = Condition.find(params[:id])
    puts @condition.fields.inspect
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def dashboard
    @hospital = Hospital.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :kitchen_sink]

  def home
  end

  def dashboard
    if current_user.paramedic?
      redirect_to new_call_path
    else
      redirect_to dashboard_hospital_path(current_user.hospital)
    end
  end

  def kitchen_sink
    @call = Call.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/calls/_show.html.erb
<div class="call-detail" id="call-<%= call.id %>" style="display: none;">
    <h2 class="<%= call.condition.category.slug %>">#<%= call.id %> <%= call.condition.name %></h2>
    <% if call.critical  == true %>
    <h1>Critical Patient Arriving!</h1>
  <% else %>
    <div class="vital-signs">
      <p><strong>Age: </strong><%= call.age %> </p>
      <p><strong>Sex: </strong><%= call.gender.capitalize %> </p>
      <p><strong>B/P: </strong><%= call.blood_pressure %> </p>
      <p><strong>Pulse: </strong><%= call.pulse %> </p>
      <p><strong>Temp: </strong><%= call.temperature %>° </p>
      <p><strong>SpO2%: </strong><%= call.spa02 %> </p>
    </div>

  <div class="condition-fields">
    <%if call.condition.name == "Chest pain" %>
      <%= render "calls/condition/chest_pain", call: call %>
    <% else %>
      <%= render "calls/condition/burn", call: call %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/calls/condition/_burn.html.erb
<% call.details.each do |detail| %>
  <p>
    <b><%= detail.name.split('_').select{ |word| !['burn'].include?(word) }.map{ |word| word.capitalize}.join(' ') %>:</b>
    <%= detail.value.kind_of?(Array) ? detail.value.map { |word| word.capitalize }.join(' ') : detail.value.capitalize %>
  </p>
<% end %>

app/views/calls/condition/_chest_pain.html.erb
<% call.details.each do |detail| %>
  <p>
    <b><%= detail.name.split('_').select{ |word| !['chest', 'pain'].include?(word)}.map{ |word| word.capitalize}.join(' ') %>:</b>
    <%= detail.value.kind_of?(Array) ? detail.value.map{ |word| word.capitalize}.join(' ') : detail.value.capitalize  %>
  </p>
<% end %>

app/views/calls/fields/_0-10_range.html.erb
<fieldset class="mb-3">
  <legend class="form-call-legend"><%= field.name.humanize %>:</legend>
  <div class = "form-call form-call-range">
    <% 11.times do |n| %>
      <label>
      <input type="radio" name="call[details[<%= field.name %>]" id="<%= n %>" value="<%= n %>">
        <div class="<%= condition.category.name.downcase %>">
          <%= n %>
        </div>
      </label>
    <% end %>
  </div>
</fieldset>

app/views/calls/fields/_boolean.html.erb
<fieldset class="mb-3">
  <legend class="form-call-legend"><%= field.name.humanize %>:</legend>
  <div class="form-call form-call-boolean">
    <% field.values.each do |value| %>
      <label>
        <input class="form-check-input" type="radio" name="call[details[<%= field.name %>]" id="<%= value %>" value="<%= value %>">
        <div class="<%= condition.category.name.downcase %>">
          <%= value %>
        </div>
      </label>
    <% end %>
  </div>
</fieldset>

app/views/calls/fields/_cards.html.erb
<% items.each do |item| %>
  <label class="labl card scroll-next">
    <%= f.radio_button item.to_fk, item.id %>
    <div>
      <%= render "#{item.to_table_name}/card", item.to_sym => item %>
    </div>
  </label>
<% end %>

app/views/calls/fields/_checkbox.html.erb
<fieldset class="mb-3">
  <legend class="form-call-legend"><%= field.name.humanize %>:</legend>
  <div class="form-call form-call-checkbox">
    <h1></h1>
    <% field.values.each do |value| %>
      <label>
        <input type="checkbox" value="<%= value %>" name="call[details[<%= field.name %>][]">
        <div class="<%= condition.category.name.downcase %>">
          <%= value %>
        </div>
      </label>
    <% end %>
  </div>
</fieldset>

app/views/calls/fields/_oxygensat.html.erb
<div class="wrapper">
  <h2>SpaO2%</h2> <%= f.text_field :spa02 %>
</div>

app/views/calls/fields/_percentage.html.erb
<legend class="form-call-legend"><%= field.name.humanize %>:</legend>
<div class="form-call form-call-percentage">
<% 11.times do |n| %>
    <% value = "#{n * 10}%" %>
    <label>
      <input type="radio" name="call[details[<%= field.name %>]" value="<%= value %>">
      <div class="<%= condition.category.name.downcase %>">
        <%= value %>
      </div>
    </label>
  <% end %>
</div>

app/views/calls/fields/_radiation.html.erb
<div class="wrapper">
  <div class = "card card-body">
    <h2 >Radiating to:</h2>
    <% field.values.each do |value| %>
      <input type="checkbox" name="call[details[radiating_to]][]" value="<%= value %>">
      <label><%= value %></label>
    <% end %>
  </div>
</div>

app/views/calls/fields/_radio.html.erb
<fieldset class="mb-3">
  <legend class="form-call-legend"><%= field.name.humanize %>:</legend>
  <div class="form-call form-call-radiobutton">
    <% field.values.each do |value| %>
      <label>
        <input type="radio" name="call[details[<%= field.name %>]" name = "<%= value %>" id="<%= value %>" value="<%= value %>">
        <div class="<%= condition.category.name.downcase %>">
          <%= value %>
        </div>
      </label>
    <% end %>
  </div>
</fieldset>

app/views/calls/fields/_time_ago.html.erb
<!-- <label style="font-size:24px, font-style:bold"> -->
<div class="form-group">
  <label for="exampleFormControlInput1" style="font-size:24px"><b><%= field.name.humanize %>:</b></label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="How long ago?" name="call[details[<%= field.name %>]">
</div>

app/views/calls/fields/_timing.html.erb
<div class= "wrapper">
  <div class="card card-body">
    <h2>Timing:</h2>
    <% field.values.each do |value| %>
      <input type="radio" name="call[details[timing]]" value="<%= value %>">
      <label><%= value %></label>
    <% end %>
  </div>
</div>

app/views/calls/new.html.erb
<% if current_user.hospital.nil? %>

  <%= simple_form_for @call, method: :post, url: calls_path, html: { class: "multi-screen-form" } do |f| %>

    <div class="form-screen">
      <div class="container">
        <div class="card-grid-hospital">
          <%= render "calls/fields/cards", f: f, items: Hospital.all %>
        </div>
      </div>
    </div>

    <div class="form-screen categories">
      <div class="container">
          <div class="categories row">
            <% Category.all.each do |category| %>
              <div class="col-6 mb-5">
                <%= link_to category.name, "#", class: "btn btn-condition #{category.slug} js-category-filter scroll-next", "data-category": category.slug %>
              </div>
            <% end %>
        </div>
      </div>
    </div>

    <div class="form-screen categories">
      <div class="js-condition-radio-buttons js-category-filter-list card-grid" style="display: none;">
        <%= render "calls/fields/cards", f: f, items: Condition.all %>
      </div>
    </div>

    <div class = "form-screen categories">
      <div class="container-vital_signs">
        <h1>Vital Signs</h1>
        <div class="row">
          <div class="col-6"><%= f.input :gender, as: :radio_buttons, collection: Call::VALID_GENDERS %></div>
          <div class="col-6"><%= f.input :age %></div>
          <div class="col-6"><%= f.input :pulse %></div>
          <div class="col-6"><%= f.input :blood_pressure %></div>
          <div class="col-6"><%= f.input :temperature %></div>
          <div class="col-6"><%= f.input :spa02 %></div>
        </div>
        <div class="row">
          <div class="col-3">
            <%= link_to "Critical", call_emergencies_path, class: "js-critical-button btn btn-danger btn-lg btn-block" %>
          </div>
          <div class="col-9">
            <button class= "btn btn-primary btn-lg btn-block scroll-next" type = "button">Next</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

<% end %>

app/views/conditions/_card.html.erb
<div data-category="<%= condition.category.slug %>" class="btn btn-condition <%= condition.category.name.downcase %>">
  <%= condition.name %>
</div>

app/views/conditions/_fields.html.erb
<% condition.fields.each_with_index do |field, index| %>
  <% if (index % fields_per_screen).zero? %>
    <div class="form-screen condition-form-screen">
      <div class="container-fluid">
        <div class="row justify-content-center">
          <div class="col-7">
  <% end %>
  <!-- Don't look up -->

  <%  if field.values == nil %>
    <%=  render "calls/fields/#{field.type}", field: field, condition: condition %>
  <% else %>
    <%=  render "calls/fields/#{field.type}", field: field, condition: condition %>
  <% end %>

  <!-- Don't look down -->
  <% if condition.fields.length - 1 == index %>
            <input type="submit" name="commit" value="Send" class="btn btn-lg btn-block btn-primary" data-disable-with="Send">
          </div>
        </div>
      </div>
    </div>
  <% elsif (index % fields_per_screen) == (fields_per_screen - 1) %>
            <button class= "btn btn-lg btn-block btn-primary scroll-next" type = "button">Next</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/conditions/fields.js.erb
var multiScreenForm = document.querySelector('.multi-screen-form')

var conditionFormScreens = document.querySelectorAll(".condition-form-screen")
conditionFormScreens.forEach((screen) => screen.remove())

var formScreensPartial = '<%= j render "conditions/fields", fields_per_screen: 5, condition: @condition %>'
multiScreenForm.insertAdjacentHTML('beforeEnd', formScreensPartial)

app/views/hospitals/_call_card.html.erb
<div class="call-card <%= call.condition.category.slug %>" data-call-id="<%= call.id %>">
  <h2 class="call-card-id">#<%= call.id %></h2>
  <h3 class="call-card-condition"><%= call.condition.name %></h3>
</div>

app/views/hospitals/_card.html.erb
<%= cl_image_tag hospital.photo.key,
  alt: hospital.name,
  class: "img-gradient",
  crop: :fill
%>
<div class="card-body">
  <h3><%= hospital.name %></h3>

  <p class="card-text"><small><%= hospital.address %></small></p>
</div>

app/views/hospitals/_dashboard.html.erb
<% if current_user.hospital %>
<h1><%= @hospital.name %></h1>
<% @hospital.calls.each do |call| %>
<div class = "container">
  <div class = "border">
    <h2 class = "font-weight-bold"><%= call.condition.name %></h2>
    <h3>Age:<%= call.age %></h3>
    <h3>Gender:<%= call.gender %></h3>
    <h3>B/P:<%= call.blood_pressure %></h3>
    <h3>Pulse:<%= call.pulse %></h3>
    <h3>Temp:<%= call.temperature %></h3>
    <h3>SpO2%<%= call.spa02 %></h3>
  </div>

  <div class="container border">
    <%if call.condition.name == "Chest pain" %>
      <%= render "calls/condition/chest_pain", call: call %>
    <% else %>
      <%= render "calls/condition/burn", call: call %>
    <% end %>
  </div>
 </div>
 <%end%>
 <%end%>

app/views/hospitals/dashboard.html.erb
<div class="call-wrapper">
  <div class="sidebar"  id="calls-bar">
    <% @hospital.calls.sort_by { |obj| obj.created_at }.reverse.each do |call| %>
      <%= render "hospitals/call_card", call: call %>
    <% end %>
  </div>

  <div class="content">

    <div class="call-info" id="call-info">
      <% @hospital.calls.each do |call| %>
        <%= render "calls/show", call: call %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    App["hospital_<%= @hospital.id %>_calls"] = App.cable.subscriptions.create({
      channel: 'HospitalChannel',
      hospital_id: <%= @hospital.id %>,
    }, {
        received: (data) => {
          // When a broadcast is received to the hospital
          const callsBar = document.querySelector("#calls-bar");
          const content = document.querySelector("#call-info");

          // Create an element to receive the card to the bar
          const element = document.createElement("div");
          // Add the call card partial to the element
          element.innerHTML = data.card;
          // Assign the handleCallClick behavior to the card
          element.querySelector(".call-card").addEventListener("click", window.handleCallClick)
          // Push the element into the cards bar
          callsBar.insertAdjacentElement("afterBegin", element);

          // Push the content of the call into the content bar
          content.insertAdjacentHTML("beforeEnd", data.content);

          // Change the currently shown content, to the current call
          window.filterCall(data.id)
      }
    })
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>
    <%# <meta name="viewport" content="width=device-width, initial-scale=1.0"/> %>
    </head>
    <style>
   @import url('https://fonts.googleapis.com/css?family=Karla:400,700|Montserrat:600i,800|Roboto+Mono&display=swap');
    </style>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
      <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-dark d-flex justify-content-center align-items-center mb-5">
  <div id = "slogan-div">
    <h1 id = "slogan-font">
      <span id="slogan"></span>
    </h1>
  </div>
</div>

<div class="you-tube text-center mb-5 vh-100 d-flex align-items-center flex-column justify-content-center">
  <h2 class = "mb-5">This is how things are done right now...</h2>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/AjMZE9S9vkQ?start=10" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<%= render 'components/footer' %>

app/views/pages/kitchen_sink.html.erb
<h2>Banner</h2>
<%= render 'components/banner' %>

<h2>Hospital Cards</h2>
<div class="container">
  <div class="row">
    <% 9.times do %>
      <div class="col-4">
         <%= render "hospitals/card", hospital: Hospital.first%>
      </div>
    <% end %>
  </div>
</div>

<h2>Buttons</h2>

  <div class="col-12">
    <%= render 'components/buttons' %>
  </div>

<%= render 'components/radio_buttons' %>




<%= render 'components/footer' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="CD3" id = "logo">CODE 3</i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About us", root_path, class: "nav-link" %>
      </li>

      <% if !user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>

      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <%= image_tag 'https://res.cloudinary.com/dgarqyquz/image/upload/v1583953209/doctor_z4lstr.jpg' , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>